#ifndef __LFIDRIVER_CTL__

#define __LFIDRIVER_CTL__

#define FSCTL_LFIDRIVER_BASE      FILE_DEVICE_UNKNOWN

#define _LFIDRIVER_CTL_CODE(_Function, _Method, _Access)  \
            CTL_CODE(FSCTL_LFIDRIVER_BASE, _Function, _Method, _Access)

#define IOCTL_LFIDRIVER_REGISTER_MODULE   \
            _LFIDRIVER_CTL_CODE(0x200, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define IOCTL_LFIDRIVER_CUSTOM_BUG   \
            _LFIDRIVER_CTL_CODE(0x201, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define IOCTL_LFIDRIVER_WINDOWS_USERMODE_BUG   \
            _LFIDRIVER_CTL_CODE(0x202, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define IOCTL_LFIDRIVER_CRASH_KERNEL   \
            _LFIDRIVER_CTL_CODE(0x203, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define IOCTL_LFIDRIVER_PS_WATCHDOG   \
            _LFIDRIVER_CTL_CODE(0x204, METHOD_BUFFERED, FILE_WRITE_ACCESS)

#endif
